# Generated by Django 3.1.5 on 2021-07-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['uid']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
